version: "3"
services:
  vulnerable-service:
    build: ./service
    container_name: vulnerable-service
    ports:
      - "5005:5005"
    volumes:
      - ./data/server_crt.pem:/app/server_crt.pem:ro
      - ./data/server_key.pem:/app/server_key.pem:ro

  vulnerable-tabpy:
    build: ./tabpy
    container_name: vulnerable-tabpy
    ports:
      - "13622:13622"
    volumes:
      - ./data/server_crt.pem:/tabpy/server_crt.pem:ro
      - ./data/server_key.pem:/tabpy/server_key.pem:ro

  attacker:
    image: dockerstore/alpine-11-with-netcat:latest
    container_name: attacker
    entrypoint: "sleep infinity"
