version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --address ":9000" --console-address ":9001" /data

  mc:
    image: minio/mc:RELEASE.2024-09-16T17-43-14Z
    container_name: mc
    depends_on:
      - minio
    volumes:
      - ./data:/data
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/compromised-bucket;
      /usr/bin/mc cp /data/benign.parquet minio/compromised-bucket/benign.parquet;
      /usr/bin/mc cp /data/malicious.parquet minio/compromised-bucket/malicious.parquet;
      exit 0;
      "

  vulnerable-service:
    build: ./service
    container_name: vulnerable-service
    ports:
      - "8080:80"

  attacker:
    image: dockerstore/alpine-11-with-netcat:latest
    container_name: attacker
    entrypoint: "sleep infinity"
